{% set version = os.environ.get('S3_DRIVER_VERSION').replace("-", "") %}

package:
  name: khiops-driver-s3
  version: {{ version }}

source:
  path: ../

build:
  number: 0
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - aws-sdk-cpp
    - zlib
    - libboost-devel
    - libboost-headers
    - fmt
    - spdlog
  run:
    - aws-crt-cpp

files:
  - lib/libkhiopsdriver_file_s3.so* [linux]
  - lib/libkhiopsdriver_file_s3*.dylib [osx]
  - lib/*.dll [win]
  - lib/*.dll [win]

about:
  home: https://khiops.org
  license: BSD+3-clause
  summary: Khiops driver to access files on Amazon S3
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiopsdriver_s3
