---
name: Test Khiops Installation
description: Test khiops' detection of installed drivers
runs:
  using: composite
  steps:
    - name: Check Khiops output [UNIXes]
      # Test if the output of Khiops in the console is as expected (no mpi or java errors)
      # We expect only one line in stdout+stderr when running 'khiops -v'
      if: runner.os != 'Windows'
      shell: bash
      env:
        KHIOPS_PROC_NUMBER: 4
        OMPI_MCA_rmaps_base_oversubscribe: true
        KHIOPS_MPI_VERBOSE: true
      run: |
        # Compute or get the khiops_env directory
        if type -P khiops_env &> /dev/null
        then
          KHIOPS_ENV_DIR=$(dirname $(type -P khiops_env))
        elif [[ -n "$CONDA_ENV_BIN_DIR" ]]
        then
          KHIOPS_ENV_DIR=$CONDA_ENV_BIN_DIR
        else
          echo "::error::This action expects CONDA_ENV_BIN_DIR to be defined"
          false
        fi
        $KHIOPS_ENV_DIR/khiops -s
        $KHIOPS_ENV_DIR/khiops -v &> output
        LINE_NUMBER=$(wc -l < output)
        if [ $LINE_NUMBER -gt 1 ] ;
        then 
          echo "::error::Unexpected output in khiops scripts"
          false
        fi
    - name: Check Khiops output [Windows]
      if: runner.os == 'Windows'
      shell: cmd /C call {0}
      env:
        KHIOPS_PROC_NUMBER: 4
      run: |
        khiops -s
        for /f %%i in (' khiops -v ^| find /c /v "" ') do set "LINE_NUMBER=%%i"
        if not "%LINE_NUMBER%" == "1" (
          echo "::error::Unexpected output in khiops scripts"
          exit 1
        )
