# Copyright (c) 2021-2022-2023-2024 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# The peculiarity of this workflow is that assumes vcpkg stored as a submodule of this repository.
# The workflow runs on x64 and ARM platforms.
# Workflow steps:
# - Setup vcpkg and cache it on the GitHub Action cloud based cache.
# - Runs CMake with CMakePreset.json using a presest configuration
#   that leverages the vcpkg's toolchain file. This will automatically run vcpkg 
#   to install dependencies described by the vcpkg.json manifest file. 
#   This stage also runs vcpkg with Binary Caching leveraging GitHub Action cache to 
#   store the built packages artifacts, hence it will be a no-op if those are restored 
#   from cache (e.g., already previously built).
# - Finally builds the sources with Ninja, and tests as well.
name: hosted-ninja-vcpkg_submod-autocache
on:
  push:
  workflow_dispatch:
  pull_request:
    branches: 
    - main

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, triplet: x64-linux}
          - {os: macos-latest, triplet: arm64-osx}
          - {os: macos-15-intel, triplet: x64-osx}
          - {os: macos-14, triplet: arm64-osx}
          - {os: windows-latest, triplet: x64-windows}
    defaults:
      run:
        shell: bash
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
    #
    # [OPTIONAL] Define the vcpkg's triplet 
    # you want to enforce, otherwise the default one 
    # for the hosting system will be automatically
    # choosen (x64 is the default on all platforms, 
    # e.g. x64-osx).
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }} 
      # S3 configuration used for testing
      AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      STORAGE_DRIVER_TEST_URL_PREFIX: s3://diod-data-di-jupyterhub
      
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - uses: lukka/get-cmake@v3.30.3

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Install coverage tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install lcov gcovr
  
      # Note: if the preset misses the "configuration", it is possible to explicitly select the
      # configuration with the additional `--config` flag, e.g.:
      #   buildPreset: 'ninja-vcpkg'
      #   buildPresetAdditionalArgs: "[`--config`, `Release`]"
      #   testPreset: 'ninja-vcpkg'
      #   testPresetAdditionalArgs: "[`--config`, `Release`]"
      - name: Build debug version and run sanitizer checks.
        if: matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-dbg'
          configurePresetAdditionalArgs: '["-DBUILD_TESTS=ON"]'
          buildPreset: 'ninja-dbg'
          testPreset: 'ninja-dbg'
        env:
          CTEST_PARALLEL_LEVEL: ''

      # GCOV seems to be broken with newer versions of GCC, so we disable it for now.
      # - name: Generate coverage report
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     cmake --build --preset ninja-vcpkg-debug --target khiops-s3_coverage --target khiops-s3_cobertura

      # - name: Upload coverage results
      #   uses: actions/upload-artifact@v7
      #   if: matrix.os == 'ubuntu-latest'
      #   with:
      #     name: coverage
      #     path: |
      #       builds/ninja-multi-vcpkg/coverage/*
      #       builds/ninja-multi-vcpkg/coverage.*
      #     if-no-files-found: ignore

      - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
        uses: lukka/run-cmake@v10
        env:
          S3_DRIVER_LOGLEVEL: debug
          CTEST_PARALLEL_LEVEL: ''
        with:
          configurePreset: 'ninja-rel'
          configurePresetAdditionalArgs: '["-DBUILD_TESTS=ON"]'
          buildPreset: 'ninja-rel'
          testPreset: 'ninja-rel'
          testPresetAdditionalArgs: '["--output-junit", "test_results.xml"]'

      - name: Upload results of cloud storage tests
        if: always()
        uses: test-summary/action@v2
        with:
          paths: ${{ github.workspace }}/build/release/test_results.xml
  
      - name: Upload the packages as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.os }}
          path: |
            build/release/lib/*.dylib
            build/release/lib/*.so
            build/release/bin/*.dll
            build/release/bin/*.lib
          if-no-files-found: ignore
