---
name: DEB Packages
on:
  workflow_dispatch:
  pull_request:
        branches: 
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        image: ['debian:11', 'debian:12',  'ubuntu:20.04', 'ubuntu:22.04', 'ubuntu:24.04']
    container: ${{ matrix.image }}
    steps:
      - name: Install packages
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt-get -y update
          apt-get -y --no-install-recommends install build-essential coreutils debhelper git ca-certificates curl 
          apt-get -y install ninja-build 
          apt-get -y install zip pkg-config # for vcpkkg
          curl -LO "https://github.com/Kitware/CMake/releases/download/v3.30.3/cmake-3.30.3-linux-x86_64.sh"
          bash cmake-3.30.3-linux-x86_64.sh --prefix=/usr/local/ --exclude-subdir
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure CMake
        run: |
          cmake -B builds -S . -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Build 
        run: |
          cmake --build builds --target khiopsdriver_file_s3
      - name: Build package with CPack
        run: cd builds/ && cpack -G DEB
      - name: Set environment variables
        run: |
          source /etc/os-release
          echo "ID=$ID" >> "$GITHUB_ENV"
          echo "VERSION_CODENAME=$VERSION_CODENAME" >> "$GITHUB_ENV"
      - name: Rename the packages to include the ubuntu codename
        run: |
          cd builds/packages/
          for filename in *.deb
          do
            mv -v $filename ${filename%_*}-${VERSION_CODENAME}.${filename##*_}
          done
      - name: Upload the packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          # We add a `deb-` prefix so we can later recover all artifacts with the pattern `deb-*`
          # Note: The more natural pattern `*-deb` or `*` does not work
          name: deb-${{ env.ID }}-${{ env.VERSION_CODENAME }}
          path: builds/packages/*.deb
          if-no-files-found: error
 
  # Test packages on a brand new runner to check:
  # - the installation process (including dependencies installation)
  # - that executable works (run with -s)
  # - that it executes a small test
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      # S3 configuration used for testing
      AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: ['debian:11', 'debian:12',  'ubuntu:20.04', 'ubuntu:22.04', 'ubuntu:24.04']
    permissions:
      contents: 'read'
      id-token: 'write'            
    container:
      image: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          source /etc/os-release
          echo "ID=$ID" >> "$GITHUB_ENV"
          echo "VERSION_CODENAME=$VERSION_CODENAME" >> "$GITHUB_ENV"
          echo "MPI_IMPLEMENTATION=${{ inputs.mpi_implementation || 'openmpi' }}" >> "$GITHUB_ENV"
      - name: Install curl
        run: |
          apt-get update
          apt-get install -y curl
      - name: Download and install Khiops core
        run: |
          curl -L https://github.com/KhiopsML/khiops/releases/download/10.3.2/khiops-core-${{ env.MPI_IMPLEMENTATION }}_10.3.2-1-${{ env.VERSION_CODENAME }}.amd64.deb --output ./khiops-core.deb
          dpkg -i ./khiops-core* || true
          apt-get -f install -y
      - name: Download artifacts (driver package)
        uses: actions/download-artifact@v4
        with:
          name: deb-${{ env.ID }}-${{ env.VERSION_CODENAME }}
          path: artifacts
      - name: Install driver
        run: dpkg -i ./artifacts/khiops-driver-*.deb
      - name: Check Khiops core installation
        uses: ./.github/actions/test-khiops-install
      - name: Test Khiops on Iris dataset
        uses: ./.github/actions/test-khiops-on-iris
        with:
          os-decription: ${{ env.ID }}-${{ env.VERSION_CODENAME }}

  # Release is only executed on tags
  release:
    if: github.ref_type == 'tag'
    # We release even if the tests fail (we delete from the release whatever fails manually)
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          # See the upload-artifact step in the build job for the explanation of this pattern
          pattern: deb-*
          merge-multiple: true
      - name: Rename packages with tag version
        run: |
         # Renames the packge only if the source version differs from the tag
         SOURCE_VERSION=$(./scripts/driver-version | sed 's/-/_/')
         TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/-/_/')
         for PKG_FILE in *.deb
         do
           NEW_PKG_FILE=$(echo $PKG_FILE | sed "s/_${SOURCE_VERSION}-/_${TAG_VERSION}-/")
           if [[ "$PKG_FILE" != "$NEW_PKG_FILE" ]]
           then
             echo "Renaming '$PKG_FILE' to '$NEW_PKG_FILE'"
             mv $PKG_FILE $NEW_PKG_FILE
           fi
         done
      - name: Upload packages to the release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: '*.deb'
          body: |
            **This release is for testing purposes only and there is no support for it.**
            **Go to https://khiops.org to install the latest supported version.**
          draft: false
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true
