---
    name: Test conda-forge Packages
    on:
      workflow_dispatch:

    defaults:
      run:
        shell: bash -el {0}
    jobs:
      test:
        strategy:
          fail-fast: false
          matrix:
            env:
              - {os: ubuntu-22.04, os-family: linux-x64}
              - {os: ubuntu-24.04, os-family: linux-x64}
              - {os: windows-2022, os-family: win-64}
              #- {os: macos-12, os-family: osx-64}
              - {os: macos-13, os-family: osx-64}
              - {os: macos-14, os-family: osx-arm64}
        runs-on: ${{ matrix.env.os }}
        permissions:
          contents: 'read'
          id-token: 'write'
        env:
          # S3 configuration used for testing
          AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
        steps:
          - name: Install Miniconda
            uses: conda-incubator/setup-miniconda@v3
            with:
              miniforge-version: latest  # needed for macOS 13
              python-version: '3.12'
              channels: conda-forge
              conda-remove-defaults: true
              activate-environment: test
          - name: Install the khiops-core and driver Conda packages
            run: conda install -c conda-forge khiops-core==10.3.2 khiops-driver-s3
          - name: Add CONDA_PREFIX to shared PATH
            shell: bash
            run: |
              if [[ $RUNNER_OS == "Windows" ]]
              then
                echo $CONDA/envs/test/Library/bin >> $GITHUB_PATH
              else
                echo "$CONDA_PREFIX/bin" >> $GITHUB_PATH
              fi
          - run: |
              conda info
              conda list
          - name: Checkout sources
            uses: actions/checkout@v4
          - name: Test that the executables are installed
            uses: ./.github/actions/test-khiops-install
          - name: Test that khiops works on Iris dataset
            uses: ./.github/actions/test-khiops-on-iris
            with:
              os-decription: ${{ matrix.env.os }}-${{ matrix.env.os-family }}    
    
